### ISSUE TITLE
Bolognese in Docker - nothing works

### ISSUE THREAD

**Issue by ChristianF88** [datacite/bolognese#198]
Hi everyone,

I just tried out the tool and I'm having a lot of issues. I'm not a `ruby` developer so I might be doing something wrong.

Here's my dockerfile:
```Dockerfile
FROM ruby:3.2
ENV LANG=C.UTF-8 \
    BUNDLER_VERSION=2.3.11
RUN apt-get update -qq && \
    apt-get install -y build-essential && \
    gem install bundler -v "$BUNDLER_VERSION"
RUN gem install bolognese
WORKDIR /app
ENTRYPOINT ["bolognese"]
```
Building the container via `docker build -t bolognese-cli .` and using the tool via `docker run --rm bolognese-cli https://doi.org/10.7554/elife.01567`.

Now when I use a "freshly" downloaded xml from datacite eg: https://api.datacite.org/application/vnd.datacite.datacite+xml/10.25678/0005jy
and I run the tool I'm getting errors for any conversion I try:
```stdout
docker run --rm bolognese-cli 0005jy.xml 
/usr/local/bundle/gems/maremma-5.0.0/lib/maremma.rb:262:in `gsub!': can't modify frozen String: "0005jy.xml" (FrozenError)
	from /usr/local/bundle/gems/maremma-5.0.0/lib/maremma.rb:262:in `block in from_xml'
	from /usr/local/bundle/gems/maremma-5.0.0/lib/maremma.rb:261:in `each'
	from /usr/local/bundle/gems/maremma-5.0.0/lib/maremma.rb:261:in `from_xml'
	from /usr/local/bundle/gems/bolognese-2.2.0/lib/bolognese/utils.rb:571:in `find_from_format_by_string'
	from /usr/local/bundle/gems/bolognese-2.2.0/lib/bolognese/utils.rb:519:in `find_from_format'
	from /usr/local/bundle/gems/bolognese-2.2.0/lib/bolognese/metadata.rb:74:in `initialize'
	from /usr/local/bundle/gems/bolognese-2.2.0/lib/bolognese/cli.rb:34:in `new'
	from /usr/local/bundle/gems/bolognese-2.2.0/lib/bolognese/cli.rb:34:in `convert'
	from /usr/local/bundle/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
	from /usr/local/bundle/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
	from /usr/local/bundle/gems/thor-1.3.2/lib/thor/base.rb:584:in `start'
	from /usr/local/bundle/gems/bolognese-2.2.0/bin/bolognese:6:in `<top (required)>'
	from /usr/local/bundle/bin/bolognese:25:in `load'
	from /usr/local/bundle/bin/bolognese:25:in `<main>'
```

If I try to get the xml via the url, it returns "garbage":
```stdout
docker run --rm bolognese-cli https://doi.org/10.25678/0005JY -t datacite
<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://datacite.org/schema/kernel-4" xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4/metadata.xsd">
  <identifier identifierType="DOI"/>
  <creators/>
  <titles/>
  <publisher/>
  <publicationYear/>
  <sizes/>
  <formats/>
  <version/>
</resource>
```

I tried all sorts of things (from argument, different conversions, different DOIs) but I am not able to get any (complete data). Any suggestions?

Thank you very much!

**Comment by ashwinisukale** [comment]
Hello Christian, could you please use Ruby version 3.1 instead of 3.2. That might solve the problem. Also use BUNDLER_VERSION=2.5.6

**Comment by ChristianF88** [comment]
Hi @ashwinisukale, thanks for your help. I tried out your suggested versions for ruby and bundler. Unfortunately, there's no difference in the outcome. It's the same output for each of the three commands that I tried (excpet now the version 2.3.2 of bolognese is installed).

```
docker run --rm bolognese-cli 0005jy.xml 
/usr/local/bundle/gems/maremma-5.0.0/lib/maremma.rb:262:in `gsub!': can't modify frozen String: "0005jy.xml" (FrozenError)
	from /usr/local/bundle/gems/maremma-5.0.0/lib/maremma.rb:262:in `block in from_xml'
	from /usr/local/bundle/gems/maremma-5.0.0/lib/maremma.rb:261:in `each'
	from /usr/local/bundle/gems/maremma-5.0.0/lib/maremma.rb:261:in `from_xml'
	from /usr/local/bundle/gems/bolognese-2.3.2/lib/bolognese/utils.rb:573:in `find_from_format_by_string'
	from /usr/local/bundle/gems/bolognese-2.3.2/lib/bolognese/utils.rb:521:in `find_from_format'
	from /usr/local/bundle/gems/bolognese-2.3.2/lib/bolognese/metadata.rb:74:in `initialize'
	from /usr/local/bundle/gems/bolognese-2.3.2/lib/bolognese/cli.rb:34:in `new'
	from /usr/local/bundle/gems/bolognese-2.3.2/lib/bolognese/cli.rb:34:in `convert'
	from /usr/local/bundle/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
	from /usr/local/bundle/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/local/bundle/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
	from /usr/local/bundle/gems/thor-1.3.2/lib/thor/base.rb:584:in `start'
	from /usr/local/bundle/gems/bolognese-2.3.2/bin/bolognese:6:in `<top (required)>'
	from /usr/local/bundle/bin/bolognese:25:in `load'
	from /usr/local/bundle/bin/bolognese:25:in `<main>'
```

Are you able to replicate my issues, with the provided docker setup?

**Comment by ChristianF88** [comment]
Hi @ashwinisukale,

I played with this a little more and got it working.

```Dockerfile
FROM ruby:3.1.6

ENV LANG=C.UTF-8 \
    BUNDLER_VERSION=2.5.6 \
    BOLOGNESE_VERSION=2.3.2

RUN apt-get update -qq && \
    apt-get install -y build-essential git && \
    gem install bundler -v "$BUNDLER_VERSION"

WORKDIR /app

RUN git clone --depth 1 --branch "$BOLOGNESE_VERSION" https://github.com/datacite/bolognese.git
RUN cd bolognese && bundle install

RUN gem install  "$BOLOGNESE_VERSION"  bolognese

ENTRYPOINT ["bolognese"]
```

I guess the dependencies weren't installed properly in my previous attempts.

You could add a slightly modified version of this. To your repository, if you want to make the tool more accessible to others. I will spare you the pull request, especially because I am not a ruby developer - so I do not know what I am doing... 

To build:
```bash
docker build -t bolognese-cli .
```

To run:
```bash
docker run --rm bolognese-cli https://doi.org/10.7554/elife.01567
```

**Comment by ChristianF88** [comment]
Improved Dockerfile:

```Dockerfile
FROM ruby:3.1.6

ENV LANG=C.UTF-8 \
    BUNDLER_VERSION=2.5.6 \
    BOLOGNESE_VERSION=2.3.2

RUN apt-get update -qq && \
    apt-get install -y build-essential git && \
    gem install bundler -v "$BUNDLER_VERSION"

WORKDIR /app

RUN git clone https://github.com/datacite/bolognese.git
RUN cd bolognese && \
    git checkout tags/$BOLOGNESE_VERSION && \
    bundle install

RUN gem install -v  $BOLOGNESE_VERSION  bolognese

ENTRYPOINT ["bolognese"]

```
